# Generated by Django 4.1.1 on 2022-09-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='senha',
            field=models.CharField(max_length=150, verbose_name='Senha'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('senha', models.CharField(max_length=150)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AnaliseSentimentos.registro')),
            ],
        ),
    ]
