# Generated by Django 4.1.1 on 2022-11-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letra',
            name='sentimento',
            field=models.TextField(default=1, max_length=100000, unique=True, verbose_name=''),
            preserve_default=False,
        ),
    ]
