# Generated by Django 4.1.1 on 2022-10-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letra',
            name='nomeM',
            field=models.CharField(max_length=150, verbose_name='Nome da Músicaaaa'),
        ),
    ]
