# Generated by Django 4.1.1 on 2022-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
