# Generated by Django 4.1.1 on 2022-11-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='email',
        ),
    ]
