# Generated by Django 4.1.1 on 2022-09-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0002_alter_registro_email_alter_registro_senha_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.TextField(max_length=150, verbose_name='Letra')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AnaliseSentimentos.login')),
            ],
        ),
    ]
