# Generated by Django 4.1.1 on 2022-11-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0002_letra_sentimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letra',
            name='login',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
