# Generated by Django 4.1.1 on 2022-12-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0003_alter_registro_email_alter_registro_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
