# Generated by Django 4.1.1 on 2022-10-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0004_alter_letra_letra_alter_letra_nomem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letra',
            name='nomeM',
            field=models.CharField(blank=True, max_length=150, verbose_name=''),
        ),
    ]
