# Generated by Django 4.1.1 on 2022-11-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0007_alter_letra_sentimento_alter_letra_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='usuario',
        ),
    ]
