# Generated by Django 4.1.1 on 2022-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnaliseSentimentos', '0008_remove_registro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='senha',
            field=models.CharField(max_length=150),
        ),
    ]
